[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "missingdescriptionfile"
authors = [
    {name = "Sir Robin", email = "robin@camelot.uk"}
]
readme = "definitely-missing.rst"
dynamic = ["version", "description"]
