[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "module1"
authors = [
    {name = "Sir Robin", email = "robin@camelot.uk"}
]
reedme = "my-description.rst"  # Deliberate typo for test
dynamic = ["version", "description"]
