[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "no_docstring"
authors = [
    {name = "Sir Robin", email = "robin@camelot.uk"}
]
readme = "EG_README.rst"
dynamic = ["version", "description"]

[project.urls]
Documentation = "https://example.com/no_docstring"
