[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "module1"
authors = [
    {name = "Sir Robin", email = "robin@camelot.uk"}
]
readme = "EG_README.rst"
dynamic = ["version", "description"]

[project.optional-dependencies]
test = ["pathlib2; python_version == \"2.7\""]
