[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "module1"
authors = [
    {name = "Sir Robin", email = "robin@camelot.uk"}
]
dynamic = ["version", "description"]

[tool.flit.sdist]
include = ["doc"]
exclude = ["doc/*.txt", "doc/**/*.md"]
