[build-system]
requires = ["flit_core"]
build-backend = "flit_core.buildapi"

[project]
name = "license_in_src"
version = "0"
description = "A test project where a license file is inside the source directory"
license-files = ["license_in_src/lic.txt"]
